# Generated by Django 4.2.1 on 2023-05-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libUser', '0002_alter_books_users_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshistory',
            name='status',
        ),
    ]
