version: '3.9'

services:
  web:
    build: .
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres
    hostname: web

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe123
    ports:
      - '5432:5432'
    hostname: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: qwe123
    ports:
      - '7002:80'
    depends_on:
      - postgres
    hostname: pgadmin
